=== supershadoe/uni-stuff/int316_mwa/e7_xml_xslt/ex7b.dtd
<!ELEMENT Software (languages, application, system)>

<!ELEMENT languages (language+)>
<!ELEMENT application (use-case+)>
<!ELEMENT system (component+)>

<!ELEMENT language (#PCDATA)>
<!ELEMENT use-case (#PCDATA)>
<!ELEMENT component (#PCDATA)>

<!ATTLIST use-case domain (medical|service|manufacturing|other) #REQUIRED>
<!ATTLIST component type (processor|motherboard|gpu|hdd|ram|other) #REQUIRED>

=== supershadoe/uni-stuff/int316_mwa/e7_xml_xslt/ex7b.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Software SYSTEM "ex7b.dtd">
<Software>
    <languages>
        <language>C</language>
        <language>C++</language>
    </languages>
    <application>
        <use-case domain="medical">Billing</use-case>
    </application>
    <system>
        <component type="processor">Intel Core i3</component>
    </system>
</Software>
